### PR TITLE
fix: process FROM scratch

### LINKED ISSUE #24: Should not report an error if base image is scratch

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #24

### CODE REVIEW

File: pkg/command/from.go [hunk 1]
```diff
@@ -21,20 +20,24 @@ import (
...
-		errs = append(errs, fmt.Errorf("unable to analyze the base image %s", node.Value))
-		return errs
-	}
-	errsFromBaseImage := AnalyzeNodeFromSource(decompiledNode, utils.Source{
-		Name: node.Value,
-		Type: utils.Parent,
-	})
-	if len(errsFromBaseImage) > 0 {
-		errs = append(errs, errsFromBaseImage...)
+	if node.Value != SCRATCH_IMAGE_NAME {
```
Comment (feloy) [inline pkg/command/from.go:27]: It is more idiomatic (and more readable) to write the happy path unindented:

```
if node.Value == SCRATCH_IMAGE_NAME {
  return nil
}
errs := []error{}
decompiledNode, err := decompiler.Decompile(node.Value)
...
```

Comment (jeffmaury) [reply pkg/command/from.go:27]: Not my preferred style (I prefer the other style as code is more compact but I'm probably biased). But we should return an empty array

Comment (feloy) [reply pkg/command/from.go:27]: Empty arrays and nil are considered inter-changeable in Go, as `len([]error{}) == len(nilArray) == 0`, `for i in range(nilArray)`, `append(arr, nilArray)` work well.

But feel free to return `[]error{}` if you prefer here

**Review by feloy — APPROVED** [review]
