### PR TITLE
fix: LABEL instruction compiled by Docker cannot be parsed

### LINKED ISSUE #16: Syntax error - can't find = in "version:-". Must be of the form: name=value
lscr.io/linuxserver/openssh-server is an image that does not work on openshift as it requires privileges.

By analyzing it with the tool, i get the error "Syntax error - can't find = in "version:-". Must be of the form: name=value"

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #16

### CODE REVIEW

File: pkg/decompiler/utils/utils.go [hunk 1]
```diff
@@ -26,21 +27,43 @@ var CONTAINERFILE_INSTRUCTIONS = []string{
...
+		return parseLabel(line, root)
+	} else {
+		result, err := parser.Parse(strings.NewReader(line))
+		if err != nil {
+			return err
+		}
+		for _, node := range result.AST.Children {
+			root.AddChild(node, -1, -1)
+		}
+	}
```
Comment (feloy) [inline pkg/decompiler/utils/utils.go:43]:
```suggestion
	}
	result, err := parser.Parse(strings.NewReader(line))
	if err != nil {
		return err
	}
	for _, node := range result.AST.Children {
		root.AddChild(node, -1, -1)
	}
```

**Review by feloy — APPROVED** [review]
