### PR TITLE
fix: Improve USER instruction processing

### LINKED ISSUE #26: Improve USER processing
There are several issues with the current implementation:

- An image without USER instruction should be considered as using root
- If a base image is using root and current image not, no error should be issued

### PR DESCRIPTION
**Pull request by jeffmaury**
This enhance USER processing:

- if no USER instruction found assume root is default and report a result
- if parent has a wrong user but child has valid USER instrution, remove result from parent 

Fixes #26

### CODE REVIEW

File: pkg/command/analyzer_test.go [hunk 1]
```diff
@@ -22,7 +22,13 @@ func TestCheckNginx(t *testing.T) {
 
 func TestFromScratch(t *testing.T) {
 	errors := AnalyzePath("resources/Containerfile.fromscratch")
-	if len(errors) > 0 {
+	if len(errors) != 1 {
 		t.Error("Image with FROM scratch returns errors")
```
Comment (feloy) [inline pkg/command/analyzer_test.go:26]: Some details on what the tests are expecting would help make the test more robust

Comment (jeffmaury) [reply pkg/command/analyzer_test.go:26]: Would be part of a follow up PR

**Review by feloy — APPROVED** [review]
